# Generated by Django 6.1.1 on 2026-09-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChoreWeekState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_states', to='shared_household_cores_organizer.chore')),
                ('covered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_week_states', to='shared_household_cores_organizer.member')),
            ],
            options={
                'ordering': ['week_start', 'chore__position', 'chore__id'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'week_start'), name='unique_chore_per_week')],
            },
        ),
    ]
