# Generated by Django 6.1.1 on 2026-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_household_cores_organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_date', models.DateField()),
            ],
        ),
    ]
